server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: pramoj
    password: pramoj
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
